# Generated by Django 4.1.6 on 2023-02-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='its your post', max_length=200),
        ),
    ]
